name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger the action when a commit is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server:  ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -f -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest ./Server
      
       # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest ./Client

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Container Instance using the updated image
      - name: Deploy to Azure Container Instance
        run: |
          az container create \
             --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
             --name ${{ secrets.AZURE_INSTANCE_CONTAINER_NAME }} \
             --cpu 1 \
             --memory 1 \
             --restart-policy Always \
             --ip-address public \
             --ports 8080 80 443 \
             --container-multi \
             --containers \
               server-app=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest \
               client-app=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest \
             --registry-login-server ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io \
             --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
             --registry-password ${{ secrets.AZURE_ACR_PASSWORD }}
      
