name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger the action when a commit is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server:  ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest ./Server
      
       # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest ./Client

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Delete existing ACI instance'
        run: |
          az container delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name aci-container-app \
            --yes

      - name: 'Save YAML config to a file'
        run: |
          echo "${{ secrets.ACI_YAML_CONFIG }}" > aci-deploy.yaml

      - name: 'Deploy ACI from YAML file'
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --file aci-deploy.yaml