name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger the action when a commit is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server:  ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest ./Server
      
       # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest ./Client

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image to Azure
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # - name: Update Azure Container Instances with new images
      #   run: |
      #    az container update \
      #      --name myContainerGroup \
      #      --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #      --containers "server-app"="${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest" \
      #                 "client-app"="${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest" \
      #      --registry-login-server ${{ secrets.AZURE_REGISTRY_NAME }} \
      #      --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
      #      --registry-password ${{ secrets.AZURE_ACR_PASSWORD }}

      # Deploy to Azure Container Instance using the updated image
      
      # - name: Deploy to Azure Container Instance
      #   run: |
      #     az container create \
      #        --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #        --name ${{ secrets.AZURE_INSTANCE_CONTAINER_NAME }} \
      #        --ip-address public \
      #        --dns-name-label yourdnslabel \
      #        --location germanywestcentral \
      #        --ports 8080 80 443 \
      #        --registry-login-server ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io \
      #        --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
      #        --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
      #        --image ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest \
      #        --image ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest
         
      # ${{ github.run_number }}
         #  --containers \
            #    name=server-app image=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest cpu=1.0 memory=1.0 ports=8080 \
            #    name=client-app image=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest cpu=1.0 memory=1.0 ports=80

      # Deploy to Azure Container Instance using the updated images
    # az container create \
    #    --name <your-container-instance-name> \
    #           --resource-group <your-resource-group> \
    #           --image <your-acr-name>.azurecr.io/client-app:<new-tag> \
    #           --image <your-acr-name>.azurecr.io/server-app:<new-tag> \
    #           --registry-login-server <your-acr-name>.azurecr.io \
    #           --registry-username <your-username> \
    #           --registry-password <your-password> \
    #           --dns-name-label <unique-dns-name> \
    #           --ports 80 443 \
    #           --environment-variables <optional-variables>

      - name: Deploy to Azure Container Instances
        uses: 'azure/aci-deploy@v1'
        with:
            resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
            dns-name-label: yourdnslabel
            image: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/server-app:latest
            cpu: 1.0
            memory: 1.0
            registry-login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
            registry-username: ${{ secrets.AZURE_ACR_USERNAME }}
            ports: 8080
            registry-password: ${{ secrets.AZURE_ACR_PASSWORD }}
            name: server-app
            location: germanywestcentral

      - name: Deploy to Azure Container Instances
        uses: 'azure/aci-deploy@v1'
        with:
            resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
            dns-name-label: yourdnslabel
            image: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/client-app:latest
            cpu: 1.0
            memory: 1.0
            registry-login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
            registry-username: ${{ secrets.AZURE_ACR_USERNAME }}
            registry-password: ${{ secrets.AZURE_ACR_PASSWORD }}
            ports: 80
            name: client-app
            location: germanywestcentral


      
